#!/usr/bin/env bash
# Displays information about a domain.

function digger_full_domain () {
    dig "www.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain www is a " $4 " record and points to " $5}'
    dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain lb-01 is a " $4 " record and points to " $5}'
    dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain web-01 is a " $4 " record and points to " $5}'
    dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain web-02 is a " $4 " record and points to " $5}'

}

function digger_sub_domain () {
    echo  -n "The subdomain $2 is a "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4 " record and points to " $5}'
}

if [ "$#" -eq 1 ]; then
     digger_full_domain "$1"

elif [ "$#" -eq 2 ]; then
     digger_sub_domain "$1" "$2"

else
     echo "Wrong usage"
fi
