#!/usr/bin/env bash
# Redirect
new_line="location /redirect_me {\\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}\\n"
apt-get update
apt-get -y install nginx
echo "Holberton School" | tee /var/www/html/index.html
sudo sed -i "42i $new_line" /etc/nginx/sites-available/default
service nginx restart
