#!/usr/bin/env bash
# custom 404 page.
apt-get update
apt-get -y install nginx
new_line="location /redirect_me {\\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}\\n"
echo "Holberton School" > /var/www/html/index.html
sed -i "41i $new_line" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
conf_404="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}"
sed -i "/server_name _;/a $conf_404" /etc/nginx/sites-available/default
service nginx restart
