#!/usr/bin/env bash
# add a custom Nginx response header
sudo apt-get update
sudo apt-get install -y nginx
new_line="add_header X-Served-By $HOSTNAME;"
sudo sed -i "20i new_line" /etc/nginx/nginx.conf
sudo service nginx restart
