#!/usr/bin/env bash
# add a custom Nginx response header
apt-get update
apt-get -y install nginx
new_line="add_header X-Served-By $HOSTNAME;"
sed -i "/sendfile on;/a $new_line" /etc/nginx/nginx.conf
service nginx restart