#!/usr/bin/env bash
# loadbalancer
apt-get -y update
apt-get -y install haproxy
echo "frontend web_front
   bind *:80
   mode http

   default_backend web_back
   backend web_back
   balance roundrobin
   server web1 35.190.151.31:80 check
   server web2 35.185.1.2:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
