#!/usr/bin/env bash
# script that gives you information about the holbertonschool
FILE="holbertonschool"
if test -e "$FILE"
then
    echo "$FILE exists"
    if test -s "$FILE"
    then
        echo "$FILE file is not empty"
    else
        echo  "$FILE holbertonschool file is empty"
    fi
    if test -f "$FILE"
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "$FILE file does not exist"
fi
